from pydantic_settings import BaseSettings

class BaseFastAPISettings(BaseSettings):
    debug: bool = ...
    api_v1_str: str = ...
    host: str = ...
    port: int = ...
    allowed_origins: str | list[str] = ...
    cors_allow_credentials: bool = ...
    cors_max_age: int = ...

class BaseDatabaseSettings(BaseSettings):
    database_url: str = ...
